# SPDX-FileCopyrightText: 2024 PNED G.I.E.
#
# SPDX-License-Identifier: Apache-2.0

name: Run Tests

on: push

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    environment: sonarcloud
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.12"
      - name: install dependencies
        run: pip install -r dev-requirements.txt && pip install -r requirements.txt
      - name: run pytest
        run: pytest --cov=. --cov-report xml:coverage.xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@59db25f34e16620e48ab4bb9e4a5dce155cb5432 # v8.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: run black
        run: black --check --verbose src
      - uses: fsfe/reuse-action@676e2d560c9a403aa252096d99fcab3e1132b0f5 # v6
